version: "3.8"

services:
  
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: