services:
  - type: web
    plan: free
    name: book-app
    runtime: image
    region: frankfurt
    image:
      url: docker.io/cajsanu/book-app:production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book-app-db
          property: connectionString
      - key: PORT
        value: 3002
      - key: SECRET
        value: secret

databases:
  - name: book-app-db
    plan: free
    region: frankfurt
