INSERT INTO books
  (title, author, year, url)
VALUES
  ('Lasse Majas detektivbyrå', 'Martin Widmark', 2002, NULL),
  ('Pennusta koiraksi', 'Tuire Kaimio', 2000, NULL),
  ('How to Train Your Dragon', 'Cressida Cowell', 2003, NULL),
  ('Momo', 'Michael Ende', 1973, NULL),
  ('Bronsdolken', 'Michelle Paver', 2006, NULL),
  ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 1997, NULL),
  ('Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 1998, NULL),
  ('Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 1999, NULL),
  ('Harry Potter and the Goblet of Fire', 'J.K. Rowling', 2000, NULL),
  ('Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 2003, NULL),
  ('Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 2005, NULL),
  ('Harry Potter and the Deathly Hallows', 'J.K. Rowling', 2007, NULL),
  ('Vargbröder', 'Michelle Paver', 2004, NULL),
  ('The Hunger Games', 'Suzanne Collins', 2008, NULL),
  ('Catching Fire', 'Suzanne Collins', 2009, NULL),
  ('Mockingjay', 'Suzanne Collins', 2010, NULL),
  ('Children''s Bible', 'Various Authors', 2000, NULL),
  ('The Maze Runner', 'James Dashner', 2009, NULL),
  ('The Scorch Trials', 'James Dashner', 2010, NULL),
  ('The Death Cure', 'James Dashner', 2011, NULL),
  ('On the Come Up', 'Angie Thomas', 2019, NULL),
  ('All the Hate You Give', 'Angie Thomas', 2017, NULL),
  ('All the Bright Places', 'Jennifer Niven', 2015, NULL),
  ('All the Light We Cannot See', 'Anthony Doerr', 2014, NULL),
  ('I''ll Give You the Sun', 'Jandy Nelson', 2014, NULL),
  ('Molly Moon', 'Georgia Byng', 2002, NULL),
  ('Becoming', 'Michelle Obama', 2018, NULL),
  ('Ten Thousand Saints', 'Eleanor Henderson', 2011, NULL),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 1866, NULL),
  ('The Call of the Wild', 'Jack London', 1903, NULL),
  ('White Fang', 'Jack London', 1906, NULL),
  ('Old Man and the Sea', 'Ernest Hemingway', 1952, NULL),
  ('The Unbearable Lightness of Being', 'Milan Kundera', 1984, NULL),
  ('Girl Online', 'Zoe Sugg', 2014, NULL),
  ('Moneyless Man', 'Mark Boyle', 2010, NULL),
  ('Life and Fate', 'Vasily Grossman', 1980, NULL),
  ('Great Expectations', 'Charles Dickens', 1861, NULL),
  ('The Catcher in the Rye', 'J.D. Salinger', 1951, NULL),
  ('The Great Gatsby', 'F. Scott Fitzgerald', 1925, NULL),
  ('To Kill a Mockingbird', 'Harper Lee', 1960, NULL),
  ('The Fault in Our Stars', 'John Green', 2012, NULL),
  ('Looking for Alaska', 'John Green', 2005, NULL),
  ('An Abundance of Katherines', 'John Green', 2006, NULL),
  ('Paper Towns', 'John Green', 2008, NULL),
  ('Turtles All the Way Down', 'John Green', 2017, NULL),
  ('The Perks of Being a Wallflower', 'Stephen Chbosky', 1999, NULL),
  ('The Alchemist', 'Paulo Coelho', 1988, NULL),
  ('The Little Prince', 'Antoine de Saint-Exupéry', 1943, NULL),
  ('The Kite Runner', 'Khaled Hosseini', 2003, NULL),
  ('A Thousand Splendid Suns', 'Khaled Hosseini', 2007, NULL),
  ('And the Mountains Echoed', 'Khaled Hosseini', 2013, NULL),
  ('The Book Thief', 'Markus Zusak', 2005, NULL),
  ('Orbiting Jupiter', 'Gary D. Schmidt', 2015, NULL),
  ('History Is All You Left Me', 'Adam Silvera', 2017, NULL),
  ('The Weight of a Thousand Feathers', 'Brian Conaghan', 2018, NULL),
  ('Shiver', 'Maggie Stiefvater', 2009, NULL),
  ('Linger', 'Maggie Stiefvater', 2010, NULL),
  ('Forever', 'Maggie Stiefvater', 2011, NULL),
  ('1984', 'George Orwell', 1949, NULL),
  ('Animal Farm', 'George Orwell', 1945, NULL),
  ('Lord of the Flies', 'William Golding', 1954, NULL),
  ('Fifty Shades of Grey', 'E. L. James', 2011, NULL),
  ('Brave New World', 'Aldous Huxley', 1932, NULL),
  ('Gulag Archipelago', 'Aleksandr Solzhenitsyn', 1973, NULL),
  ('The Book of Love', 'Unknown Author', 2023, NULL),
  ('Me Before You', 'Jojo Moyes', 2012, NULL),
  ('After You', 'Jojo Moyes', 2015, NULL),
  ('Mio Min Mio', 'Astrid Lindgren', 1954, NULL),
  ('Half of a Yellow Sun', 'Chimamanda Ngozi Adichie', 2006, NULL),
  ('Wuthering Heights', 'Emily Brontë', 1847, NULL),
  ('For Whom the Bell Tolls', 'Ernest Hemingway', 1940, NULL),
  ('The Book That Wouldn''t Burn', 'Unknown Author', 2023, NULL),
  ('12 Rules for Life', 'Jordan Peterson', 2018, NULL),
  ('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, NULL),
  ('The Nordic Welfare State in Three Eras', 'Unknown Author', 2023, NULL),
  ('Malcolm Payne', 'Unknown Author', 2023, NULL),
  ('Dune', 'Frank Herbert', 1965, NULL),
  ('Everything Everything', 'Nicola Yoon', 2015, NULL),
  ('Everything I Have Learned, I''ve Learned from My Cat', 'Suzy Becker', 1990, NULL),
  ('Hope', 'Unknown Author', 2023, NULL),
  ('Underwater Dogs', 'Seth Casteel', 2012, NULL),
  ('Bob', 'Wendy Mass', 2018, NULL),
  ('Chinese Fairytales', 'Unknown Author', 2023, NULL),
  ('Love Is All You Need', 'John Lennon', 1967, NULL),
  ('Girl on the Train', 'Paula Hawkins', 2015, NULL),
  ('Holding Up the Universe', 'Jennifer Niven', 2016, NULL),
  ('In Order to Live', 'Yeonmi Park', 2015, NULL),
  ('Last Family in England', 'Matt Haig', 2004, NULL),
  ('Dark Places', 'Gillian Flynn', 2009, NULL),
  ('I Owe You One', 'Sophie Kinsella', 2019, NULL),
  ('Uni Book', 'Unknown Author', 2023, NULL),
  ('Nyckeln', 'Mats Strandberg', 2013, NULL),
  ('Utvald', 'P.C. Cast', 2007, NULL),
  ('Korsad', 'Jessica Shirvington', 2012, NULL),
  ('Doktor Proktor', 'Jo Nesbø', 2007, NULL),
  ('End of Story', 'Lydia Davis', 2014, NULL),
  ('Gather the Girls', 'Jessie Burton', 2018, NULL),
  ('Suicide Club', 'Rachel Heng', 2018, NULL),
  ('A Map for Wrecked Girls', 'Jessica Taylor', 2017, NULL),
  ('Only Child', 'Rhiannon Navin', 2018, NULL),
  ('Divergent', 'Veronica Roth', 2011, NULL),
  ('If All the Cats Disappeared from the World', 'Genki Kawamura', 2012, NULL),
  ('Only Love Can Break Your Heart', 'Ed Tarkington', 2016, NULL),
  ('Master and Margarita', 'Mikhail Bulgakov', 1967, NULL),
  ('The Hero of Our Time', 'Mikhail Lermontov', 1840, NULL),
  ('Вредные советы', 'Grigory Oster', 1983, NULL),
  ('Bible for Children', 'Various Authors', 2000, NULL),
  ('Fathers and Sons', 'Ivan Turgenev', 1862, NULL),
  ('Stories of Singrid and Guldur', 'J.R.R. Tolkien', 1954, NULL),
  ('A Game of Thrones', 'George R.R. Martin', 1996, NULL),
  ('Eugene Onegin', 'Alexander Pushkin', 1833, NULL),
  ('War and Peace', 'Leo Tolstoy', 1869, NULL),
  ('Dead Souls', 'Nikolai Gogol', 1842, NULL),
  ('Sherlock Holmes: Stories and The Hound of the Baskervilles', 'Arthur Conan Doyle', 1902, NULL),
  ('Guts', 'Chuck Palahniuk', 2005, NULL),
  ('Misery from Smartness (Горе от ума)', 'Alexander Griboyedov', 1825, NULL),
  ('The Captain''s Daughter', 'Alexander Pushkin', 1836, NULL),
  ('The Government Inspector (Revisor)', 'Nikolai Gogol', 1836, NULL),
  ('Mumu', 'Ivan Turgenev', 1854, NULL),
  ('Heart of a Dog', 'Mikhail Bulgakov', 1925, NULL),
  ('Oblomov', 'Ivan Goncharov', 1859, NULL),
  ('The Cherry Orchard', 'Anton Chekhov', 1904, NULL),
  ('About Love', 'Anton Chekhov', 1898, NULL),
  ('Robinson Crusoe', 'Daniel Defoe', 1719, NULL),
  ('Treasure Island', 'Robert Louis Stevenson', 1883, NULL),
  ('The Adventures of Tom Sawyer', 'Mark Twain', 1876, NULL),
  ('Taras Bulba', 'Nikolai Gogol', 1835, NULL),
  ('Ruslan and Ludmila', 'Alexander Pushkin', 1820, NULL),
  ('Mtsyri', 'Mikhail Lermontov', 1840, NULL),
  ('Who Lives Well in Russia (Кому на Руси жить хорошо)', 'Nikolai Nekrasov', 1873, NULL),
  ('The Queen of Spades', 'Alexander Pushkin', 1834, NULL),
  ('Childhood', 'Leo Tolstoy', 1852, NULL),
  ('At the Bottom', 'Maxim Gorky', 1902, NULL),
  ('The Portrait of Dorian Gray', 'Oscar Wilde', 1890, NULL),
  ('One Day in the Life of Ivan Denisovich', 'Aleksandr Solzhenitsyn', 1962, NULL),
  ('The Wonderful Wizard of Oz', 'L. Frank Baum', 1900, NULL),
  ('White Bim Black Ear', 'Gavriil Troepolsky', 1971, NULL),
  ('The Silver Hoof', 'Pavel Bazhov', 1939, NULL),
  ('The Young Guard', 'Alexander Fadeyev', 1945, NULL),
  ('The Enchanted Wanderer (Очарованный странник)', 'Nikolai Leskov', 1873, NULL),
  ('Selected Stories', 'Anton Chekhov', 1886, NULL),
  ('Matryona''s Home (Матрёнин двор)', 'Aleksandr Solzhenitsyn', 1959, NULL),
  ('The Gentleman from San Francisco (Господин из Сан-Франциско)', 'Ivan Bunin', 1915, NULL),
  ('Faust', 'Johann Wolfgang von Goethe', 1808, NULL),
  ('Beyond Good and Evil', 'Friedrich Nietzsche', 1886, NULL),
  ('Les Misérables', 'Victor Hugo', 1862, NULL),
  ('Atlas Shrugged', 'Ayn Rand', 1957, NULL),
  ('Cracking the Coding Interview', 'Gayle Laakmann McDowell', 2011, NULL),
  ('The Autobiography of Benjamin Franklin', 'Benjamin Franklin', 1791, NULL),
  ('Screw It, Let''s Do It', 'Richard Branson', 2006, NULL),
  ('Clean Code', 'Robert C. Martin', 2008, NULL),
  ('Deep Work', 'Cal Newport', 2016, NULL),
  ('So Good They Can''t Ignore You', 'Cal Newport', 2012, NULL),
  ('12 More Rules for Life: Beyond Order', 'Jordan Peterson', 2021, NULL),
  ('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, NULL),
  ('The Demons', 'Fyodor Dostoevsky', 1872, NULL),
  ('Rich Dad Poor Dad', 'Robert Kiyosaki', 1997, NULL),
  ('Man''s Search for Meaning', 'Viktor Frankl', 1946, NULL),
  ('Työmiehen Vaimo', 'Minna Canth', 1885, NULL),
  ('The Pragmatic Programmer', 'Andrew Hunt and David Thomas', 1999, NULL),
  ('The Mythical Man-Month', 'Frederick P. Brooks Jr.', 1975, NULL),
  ('Designing Data-Intensive Applications', 'Martin Kleppmann', 2017, NULL),
  ('The Magic of Thinking Big', 'David J. Schwartz', 1959, NULL),
  ('A Philosophy of Software Design', 'John Ousterhout', 2018, NULL),
  ('The Compound Effect', 'Darren Hardy', 2010, NULL),
  ('Meditations', 'Marcus Aurelius', 180, NULL),
  ('The Fountainhead', 'Ayn Rand', 1943, NULL),
  ('Selfishness as a Virtue', 'Ayn Rand', 1964, NULL),
  ('Nicomachean Ethics', 'Aristotle', 350, NULL),
  ('Power', 'Robert Greene', 1998, NULL),
  ('Mastery', 'Robert Greene', 2012, NULL),
  ('Sapiens', 'Yuval Noah Harari', 2011, NULL),
  ('21 Lessons for the 21st Century', 'Yuval Noah Harari', 2018, NULL),
  ('A Farewell to Arms', 'Ernest Hemingway', 1929, NULL),
  ('Pride and Prejudice', 'Jane Austen', 1813, NULL),
  ('The Road to Wigan Pier', 'George Orwell', 1937, NULL),
  ('Zorba the Greek', 'Nikos Kazantzakis', 1946, NULL),
  ('How to Win Friends and Influence People', 'Dale Carnegie', 1936, NULL),
  ('Fundamentals of Software Architecture', 'Mark Richards and Neal Ford', 2020, NULL),
  ('Software Architecture: The Hard Parts', 'Neal Ford, Mark Richards, Pramod Sadalage, Zhamak Dehghani', 2021, NULL),
  ('Never Split the Difference', 'Chris Voss', 2016, NULL),
  ('The Hobbit', 'J.R.R. Tolkien', 1937, NULL),
  ('Leadership and Self-Deception', 'The Arbinger Institute', 2000, NULL),
  ('The Outsider', 'Albert Camus', 1942, NULL);
