-- read_books_lists for books from ID 1 to ID 20 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(1, 1, 'A thrilling and suspenseful read.', 5),
(2, 1, 'Kept me on the edge of my seat.', 5),
(3, 1, 'Great plot twists and characters.', 5),
(4, 1, 'Well-written and captivating.', 4),
(5, 1, 'Couldn''t put it down.', 5),
(6, 1, 'Highly recommend this book!', 4),

(7, 2, 'An emotional rollercoaster.', 5),
(8, 2, 'Heartfelt and beautifully written.', 5),
(9, 2, 'Loved the characters and their journey.', 5),
(10, 2, 'Touching and memorable.', 4),
(11, 2, 'Couldn''t put it down.', 5),
(12, 2, 'Highly recommend this novel.', 4),

(13, 3, 'A gripping and atmospheric thriller.', 5),
(14, 3, 'Kept me guessing until the end.', 5),
(15, 3, 'Great suspense and plot twists.', 5),
(16, 3, 'Well-developed characters.', 4),
(17, 3, 'A thrilling read.', 5),
(18, 3, 'Highly recommend for thriller fans.', 4),

(19, 4, 'A heartwarming and uplifting story.', 5),
(20, 4, 'Loved the bond between the characters.', 5),
(21, 4, 'Emotionally powerful.', 5),
(22, 4, 'Touching and beautifully written.', 4),
(23, 4, 'Couldn''t put it down.', 5),
(24, 4, 'Highly recommend this novel.', 4),

(1, 5, 'A gripping and emotional journey.', 5),
(2, 5, 'Loved the intertwining stories.', 5),
(3, 5, 'Complex characters and relationships.', 5),
(4, 5, 'Kept me engaged throughout.', 4),
(5, 5, 'Couldn''t put it down.', 5),
(6, 5, 'Highly recommend this book.', 4),

(7, 6, 'A thought-provoking exploration of identity.', 5),
(8, 6, 'Lyrical prose and deep themes.', 5),
(9, 6, 'Beautifully written and profound.', 5),
(10, 6, 'Captivating from start to finish.', 4),
(11, 6, 'A unique and memorable read.', 5),
(12, 6, 'Highly recommend this novel.', 4),

(13, 7, 'A compelling and atmospheric tale.', 5),
(14, 7, 'Loved the setting and suspense.', 5),
(15, 7, 'Well-crafted characters and plot.', 5),
(16, 7, 'Kept me guessing until the end.', 4),
(17, 7, 'A gripping read.', 5),
(18, 7, 'Highly recommend for mystery fans.', 4),

(19, 8, 'An emotional and powerful story.', 5),
(20, 8, 'Loved the exploration of family dynamics.', 5),
(21, 8, 'Heartfelt and beautifully written.', 5),
(22, 8, 'Touching and memorable.', 4),
(23, 8, 'Couldn''t put it down.', 5),
(24, 8, 'Highly recommend this novel.', 4),

(1, 9, 'A gripping and atmospheric mystery.', 5),
(2, 9, 'Kept me guessing until the end.', 5),
(3, 9, 'Well-crafted plot and characters.', 5),
(4, 9, 'Engaging and suspenseful.', 4),
(5, 9, 'A thrilling read.', 5),
(6, 9, 'Highly recommend for mystery fans.', 4),

(7, 10, 'An emotional and powerful story.', 5),
(8, 10, 'Loved the exploration of family dynamics.', 5),
(9, 10, 'Heartfelt and beautifully written.', 5),
(10, 10, 'Touching and memorable.', 4),
(11, 10, 'Couldn''t put it down.', 5),
(12, 10, 'Highly recommend this novel.', 4),

(13, 11, 'A gripping and emotional journey.', 5),
(14, 11, 'Loved the intertwining stories.', 5),
(15, 11, 'Complex characters and relationships.', 5),
(16, 11, 'Kept me engaged throughout.', 4),
(17, 11, 'Couldn''t put it down.', 5),
(18, 11, 'Highly recommend this book.', 4),

(19, 12, 'A thought-provoking exploration of memory.', 5),
(20, 12, 'Lyrical prose and deep themes.', 5),
(21, 12, 'Beautifully written and haunting.', 5),
(22, 12, 'Captivating from start to finish.', 4),
(23, 12, 'A unique and memorable read.', 5),
(24, 12, 'Highly recommend this novel.', 4),

(1, 13, 'A compelling and atmospheric tale.', 5),
(2, 13, 'Loved the eerie setting and suspense.', 5),
(3, 13, 'Well-crafted characters and plot.', 5),
(4, 13, 'Kept me guessing until the end.', 4),
(5, 13, 'A haunting and gripping read.', 5),
(6, 13, 'Highly recommend for mystery fans.', 4),

(7, 14, 'An emotional and powerful story.', 5),
(8, 14, 'Loved the exploration of family dynamics.', 5),
(9, 14, 'Heartfelt and beautifully written.', 5),
(10, 14, 'Touching and memorable.', 4),
(11, 14, 'Couldn''t put it down.', 5),
(12, 14, 'Highly recommend this novel.', 4),

(13, 15, 'A gripping and atmospheric mystery.', 5),
(14, 15, 'Kept me guessing until the end.', 5),
(15, 15, 'Well-crafted plot and characters.', 5),
(16, 15, 'Engaging and suspenseful.', 4),
(17, 15, 'A thrilling read.', 5),
(18, 15, 'Highly recommend for mystery fans.', 4),

(19, 16, 'An emotional and powerful story.', 5),
(20, 16, 'Loved the exploration of family dynamics.', 5),
(21, 16, 'Heartfelt and beautifully written.', 5),
(22, 16, 'Touching and memorable.', 4),
(23, 16, 'Couldn''t put it down.', 5),
(24, 16, 'Highly recommend this novel.', 4),

(1, 17, 'A gripping and emotional journey.', 5),
(2, 17, 'Loved the intertwining stories.', 5),
(3, 17, 'Complex characters and relationships.', 5),
(4, 17, 'Kept me engaged throughout.', 4),
(5, 17, 'Couldn''t put it down.', 5),
(6, 17, 'Highly recommend this book.', 4),

(7, 18, 'A thought-provoking exploration of memory.', 5),
(8, 18, 'Lyrical prose and deep themes.', 5),
(9, 18, 'Beautifully written and haunting.', 5),
(10, 18, 'Captivating from start to finish.', 4),
(11, 18, 'A unique and memorable read.', 5),
(12, 18, 'Highly recommend this novel.', 4),

(13, 19, 'A compelling and atmospheric tale.', 5),
(14, 19, 'Loved the setting and suspense.', 5),
(15, 19, 'Well-crafted characters and plot.', 5),
(16, 19, 'Kept me guessing until the end.', 4),
(17, 19, 'A gripping read.', 5),
(18, 19, 'Highly recommend for mystery fans.', 4),

(19, 20, 'An emotional and powerful story.', 5),
(20, 20, 'Loved the exploration of family dynamics.', 5),
(21, 20, 'Heartfelt and beautifully written.', 5),
(22, 20, 'Touching and memorable.', 4),
(23, 20, 'Couldn''t put it down.', 5),
(24, 20, 'Highly recommend this novel.', 4);


-- read_books_lists for books from ID 21 to ID 30 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(1, 21, 'A gripping and emotional journey.', 5),
(2, 21, 'Loved the intertwining stories.', 5),
(3, 21, 'Complex characters and relationships.', 5),
(4, 21, 'Kept me engaged throughout.', 4),
(5, 21, 'Couldn''t put it down.', 5),
(6, 21, 'Highly recommend this book.', 4),

(7, 22, 'A thought-provoking exploration of identity.', 5),
(8, 22, 'Lyrical prose and deep themes.', 5),
(9, 22, 'Beautifully written and profound.', 5),
(10, 22, 'Captivating from start to finish.', 4),
(11, 22, 'A unique and memorable read.', 5),
(12, 22, 'Highly recommend this novel.', 4),

(13, 23, 'A compelling and atmospheric tale.', 5),
(14, 23, 'Loved the setting and suspense.', 5),
(15, 23, 'Well-crafted characters and plot.', 5),
(16, 23, 'Kept me guessing until the end.', 4),
(17, 23, 'A gripping read.', 5),
(18, 23, 'Highly recommend for mystery fans.', 4),

(19, 24, 'An emotional and powerful story.', 5),
(20, 24, 'Loved the exploration of family dynamics.', 5),
(21, 24, 'Heartfelt and beautifully written.', 5),
(22, 24, 'Touching and memorable.', 4),
(23, 24, 'Couldn''t put it down.', 5),
(24, 24, 'Highly recommend this novel.', 4),

(1, 25, 'A gripping and atmospheric mystery.', 5),
(2, 25, 'Kept me guessing until the end.', 5),
(3, 25, 'Well-crafted plot and characters.', 5),
(4, 25, 'Engaging and suspenseful.', 4),
(5, 25, 'A thrilling read.', 5),
(6, 25, 'Highly recommend for mystery fans.', 4),

(7, 26, 'An emotional and powerful story.', 5),
(8, 26, 'Loved the exploration of family dynamics.', 5),
(9, 26, 'Heartfelt and beautifully written.', 5),
(10, 26, 'Touching and memorable.', 4),
(11, 26, 'Couldn''t put it down.', 5),
(12, 26, 'Highly recommend this novel.', 4),

(13, 27, 'A gripping and emotional journey.', 5),
(14, 27, 'Loved the intertwining stories.', 5),
(15, 27, 'Complex characters and relationships.', 5),
(16, 27, 'Kept me engaged throughout.', 4),
(17, 27, 'Couldn''t put it down.', 5),
(18, 27, 'Highly recommend this book.', 4),

(19, 28, 'A thought-provoking exploration of memory.', 2),
(20, 28, 'Lyrical prose and deep themes.', 2),
(21, 28, 'Beautifully written and haunting.', 5),
(22, 28, 'Captivating from start to finish.', 4),
(23, 28, 'A unique and memorable read.', 5),
(24, 28, 'Highly recommend this novel.', 4),

(1, 29, 'A compelling and atmospheric tale.', 5),
(2, 29, 'Loved the setting and suspense.', 5),
(3, 29, 'Well-crafted characters and plot.', 5),
(4, 29, 'Kept me guessing until the end.', 4),
(5, 29, 'A gripping read.', 5),
(6, 29, 'Highly recommend for mystery fans.', 4),

(7, 30, 'An emotional and powerful story.', 5),
(8, 30, 'Loved the exploration of family dynamics.', 5),
(9, 30, 'Heartfelt and beautifully written.', 5),
(10, 30, 'Touching and memorable.', 4),
(11, 30, 'Couldn''t put it down.', 5),
(12, 30, 'Highly recommend this novel.', 4);


-- read_books_lists for books from ID 31 to ID 40 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(13, 31, 'A gripping and emotional journey.', 5),
(14, 31, 'Loved the intertwining stories.', 2),
(15, 31, 'Complex characters and relationships.', 2),
(16, 31, 'Kept me engaged throughout.', 4),
(17, 31, 'Couldn''t put it down.', 2),
(18, 31, 'Highly recommend this book.', 4),

(19, 32, 'A thought-provoking exploration of memory.', 2),
(20, 32, 'Lyrical prose and deep themes.', 2),
(1, 32, 'Beautifully written and haunting.', 2),
(2, 32, 'Captivating from start to finish.', 4),
(3, 32, 'A unique and memorable read.', 2),
(4, 32, 'Highly recommend this novel.', 4),

(5, 33, 'A compelling and atmospheric tale.', 2),
(6, 33, 'Loved the setting and suspense.', 5),
(7, 33, 'Well-crafted characters and plot.', 5),
(8, 33, 'Kept me guessing until the end.', 4),
(9, 33, 'A gripping read.', 5),
(10, 33, 'Highly recommend for mystery fans.', 4),

(11, 34, 'An emotional and powerful story.', 5),
(12, 34, 'Loved the exploration of family dynamics.', 5),
(13, 34, 'Heartfelt and beautifully written.', 5),
(14, 34, 'Touching and memorable.', 4),
(15, 34, 'Couldn''t put it down.', 5),
(16, 34, 'Highly recommend this novel.', 4),

(17, 35, 'A gripping and atmospheric mystery.', 5),
(18, 35, 'Kept me guessing until the end.', 5),
(19, 35, 'Well-crafted plot and characters.', 5),
(20, 35, 'Engaging and suspenseful.', 4),
(1, 35, 'A thrilling read.', 5),
(2, 35, 'Highly recommend for mystery fans.', 4),

(3, 36, 'An emotional and powerful story.', 2),
(4, 36, 'Loved the exploration of family dynamics.', 2),
(5, 36, 'Heartfelt and beautifully written.', 2),
(6, 36, 'Touching and memorable.', 4),
(7, 36, 'Couldn''t put it down.', 2),
(8, 36, 'Highly recommend this novel.', 4),

(9, 37, 'A gripping and emotional journey.', 2),
(10, 37, 'Loved the intertwining stories.', 2),
(11, 37, 'Complex characters and relationships.', 2),
(12, 37, 'Kept me engaged throughout.', 4),
(13, 37, 'Couldn''t put it down.', 5),
(14, 37, 'Highly recommend this book.', 4),

(15, 38, 'A thought-provoking exploration of memory.', 5),
(16, 38, 'Lyrical prose and deep themes.', 5),
(17, 38, 'Beautifully written and haunting.', 5),
(18, 38, 'Captivating from start to finish.', 4),
(19, 38, 'A unique and memorable read.', 5),
(20, 38, 'Highly recommend this novel.', 4),

(1, 39, 'A compelling and atmospheric tale.', 5),
(2, 39, 'Loved the setting and suspense.', 5),
(3, 39, 'Well-crafted characters and plot.', 5),
(4, 39, 'Kept me guessing until the end.', 4),
(5, 39, 'A gripping read.', 5),
(6, 39, 'Highly recommend for mystery fans.', 4),

(7, 40, 'An emotional and powerful story.', 5),
(8, 40, 'Loved the exploration of family dynamics.', 5),
(9, 40, 'Heartfelt and beautifully written.', 2),
(10, 40, 'Touching and memorable.', 4),
(11, 40, 'Couldn''t put it down.', 2),
(12, 40, 'Highly recommend this novel.', 4);

-- read_books_lists for books from ID 41 to ID 50 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(13, 41, 'A gripping and emotional journey.', 2),
(14, 41, 'Loved the intertwining stories.', 2),
(15, 41, 'Complex characters and relationships.', 2),
(16, 41, 'Kept me engaged throughout.', 4),
(17, 41, 'Couldn''t put it down.', 5),
(18, 41, 'Highly recommend this book.', 4),

(19, 42, 'A thought-provoking exploration of memory.', 5),
(20, 42, 'Lyrical prose and deep themes.', 5),
(1, 42, 'Beautifully written and haunting.', 5),
(2, 42, 'Captivating from start to finish.', 4),
(3, 42, 'A unique and memorable read.', 5),
(4, 42, 'Highly recommend this novel.', 4),

(5, 43, 'A compelling and atmospheric tale.', 5),
(6, 43, 'Loved the setting and suspense.', 5),
(7, 43, 'Well-crafted characters and plot.', 5),
(8, 43, 'Kept me guessing until the end.', 4),
(9, 43, 'A gripping read.', 5),
(10, 43, 'Highly recommend for mystery fans.', 4),

(11, 44, 'An emotional and powerful story.', 5),
(12, 44, 'Loved the exploration of family dynamics.', 2),
(13, 44, 'Heartfelt and beautifully written.', 2),
(14, 44, 'Touching and memorable.', 4),
(15, 44, 'Couldn''t put it down.', 5),
(16, 44, 'Highly recommend this novel.', 4),

(17, 45, 'A gripping and atmospheric mystery.', 5),
(18, 45, 'Kept me guessing until the end.', 5),
(19, 45, 'Well-crafted plot and characters.', 5),
(20, 45, 'Engaging and suspenseful.', 4),
(1, 45, 'A thrilling read.', 5),
(2, 45, 'Highly recommend for mystery fans.', 4),

(3, 46, 'An emotional and powerful story.', 5),
(4, 46, 'Loved the exploration of family dynamics.', 5),
(5, 46, 'Heartfelt and beautifully written.', 2),
(6, 46, 'Touching and memorable.', 4),
(7, 46, 'Couldn''t put it down.', 2),
(8, 46, 'Highly recommend this novel.', 4),

(9, 47, 'A gripping and emotional journey.', 5),
(10, 47, 'Loved the intertwining stories.', 5),
(11, 47, 'Complex characters and relationships.', 5),
(12, 47, 'Kept me engaged throughout.', 4),
(13, 47, 'Couldn''t put it down.', 5),
(14, 47, 'Highly recommend this book.', 4),

(15, 48, 'A thought-provoking exploration of memory.', 5),
(16, 48, 'Lyrical prose and deep themes.', 5),
(17, 48, 'Beautifully written and haunting.', 5),
(18, 48, 'Captivating from start to finish.', 4),
(19, 48, 'A unique and memorable read.', 5),
(20, 48, 'Highly recommend this novel.', 4),

(1, 49, 'A compelling and atmospheric tale.', 2),
(2, 49, 'Loved the setting and suspense.', 2),
(3, 49, 'Well-crafted characters and plot.', 5),
(4, 49, 'Kept me guessing until the end.', 4),
(5, 49, 'A gripping read.', 5),
(6, 49, 'Highly recommend for mystery fans.', 4),

(7, 50, 'An emotional and powerful story.', 5),
(8, 50, 'Loved the exploration of family dynamics.', 5),
(9, 50, 'Heartfelt and beautifully written.', 5),
(10, 50, 'Touching and memorable.', 4),
(11, 50, 'Couldn''t put it down.', 5),
(12, 50, 'Highly recommend this novel.', 4);

-- read_books_lists for books from ID 51 to ID 60 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(11, 51, 'Couldn''t put it down.', 5),
(12, 51, 'Highly recommend this novel.', 4),
(13, 52, 'A gripping and atmospheric mystery.', 5),
(14, 52, 'Kept me guessing until the end.', 5),
(15, 52, 'Well-crafted plot and characters.', 5),
(16, 52, 'Engaging and suspenseful.', 4),
(17, 52, 'A thrilling read.', 5),
(18, 52, 'Highly recommend for mystery fans.', 4),
(19, 53, 'An emotional and powerful story.', 5),
(20, 53, 'Loved the exploration of family dynamics.', 5),
(1, 53, 'Heartfelt and beautifully written.', 5),
(2, 53, 'Touching and memorable.', 4),
(3, 53, 'Couldn''t put it down.', 5),
(4, 53, 'Highly recommend this novel.', 4),
(5, 54, 'A gripping and emotional journey.', 5),
(6, 54, 'Loved the intertwining stories.', 5),
(7, 54, 'Complex characters and relationships.', 5),
(8, 54, 'Kept me engaged throughout.', 4),
(9, 54, 'Couldn''t put it down.', 5),
(10, 54, 'Highly recommend this book.', 4),
(11, 55, 'A thought-provoking exploration of memory.', 2),
(12, 55, 'Lyrical prose and deep themes.', 2),
(13, 55, 'Beautifully written and haunting.', 2),
(14, 55, 'Captivating from start to finish.', 4),
(15, 55, 'A unique and memorable read.', 2),
(16, 55, 'Highly recommend this novel.', 4),
(17, 56, 'A compelling and atmospheric tale.', 2),
(18, 56, 'Loved the setting and suspense.', 5),
(19, 56, 'Well-crafted characters and plot.', 5),
(20, 56, 'Kept me guessing until the end.', 4),
(1, 56, 'A gripping read.', 5),
(2, 56, 'Highly recommend for mystery fans.', 4),
(3, 57, 'An emotional and powerful story.', 5),
(4, 57, 'Loved the exploration of family dynamics.', 5),
(5, 57, 'Heartfelt and beautifully written.', 5),
(6, 57, 'Touching and memorable.', 4),
(7, 57, 'Couldn''t put it down.', 5),
(8, 57, 'Highly recommend this novel.', 4),
(9, 58, 'A gripping and emotional journey.', 5),
(10, 58, 'Loved the intertwining stories.', 5),
(11, 58, 'Complex characters and relationships.', 5),
(12, 58, 'Kept me engaged throughout.', 4),
(13, 58, 'Couldn''t put it down.', 5),
(14, 58, 'Highly recommend this book.', 4),
(15, 59, 'A thought-provoking exploration of memory.', 1),
(16, 59, 'Lyrical prose and deep themes.', 5),
(17, 59, 'Beautifully written and haunting.', 5),
(18, 59, 'Captivating from start to finish.', 4),
(19, 59, 'A unique and memorable read.', 5),
(20, 59, 'Highly recommend this novel.', 4),
(1, 60, 'A compelling and atmospheric tale.', 5),
(2, 60, 'Loved the setting and suspense.', 5),
(3, 60, 'Well-crafted characters and plot.', 5),
(4, 60, 'Kept me guessing until the end.', 4),
(5, 60, 'A gripping read.', 5),
(6, 60, 'Highly recommend for mystery fans.', 4);

-- read_books_lists for books from ID 61 to ID 70 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(7, 61, 'An emotional and powerful story.', 5),
(8, 61, 'Loved the exploration of family dynamics.', 1),
(9, 61, 'Heartfelt and beautifully written.', 1),
(10, 61, 'Touching and memorable.', 4),
(11, 61, 'Couldn''t put it down.', 1),
(12, 61, 'Highly recommend this novel.', 4),
(13, 62, 'A gripping and atmospheric mystery.', 1),
(14, 62, 'Kept me guessing until the end.', 1),
(15, 62, 'Well-crafted plot and characters.', 1),
(16, 62, 'Engaging and suspenseful.', 4),
(17, 62, 'A thrilling read.', 5),
(18, 62, 'Highly recommend for mystery fans.', 4),
(19, 63, 'An emotional and powerful story.', 5),
(20, 63, 'Loved the exploration of family dynamics.', 5),
(1, 63, 'Heartfelt and beautifully written.', 5),
(2, 63, 'Touching and memorable.', 4),
(3, 63, 'Couldn''t put it down.', 5),
(4, 63, 'Highly recommend this novel.', 4),
(5, 64, 'A gripping and emotional journey.', 5),
(6, 64, 'Loved the intertwining stories.', 5),
(7, 64, 'Complex characters and relationships.', 5),
(8, 64, 'Kept me engaged throughout.', 4),
(9, 64, 'Couldn''t put it down.', 5),
(10, 64, 'Highly recommend this book.', 4),
(11, 65, 'A thought-provoking exploration of memory.', 5),
(12, 65, 'Lyrical prose and deep themes.', 5),
(13, 65, 'Beautifully written and haunting.', 5),
(14, 65, 'Captivating from start to finish.', 4),
(15, 65, 'A unique and memorable read.', 5),
(16, 65, 'Highly recommend this novel.', 4),
(17, 66, 'A compelling and atmospheric tale.', 3),
(18, 66, 'Loved the setting and suspense.', 3),
(19, 66, 'Well-crafted characters and plot.', 3),
(20, 66, 'Kept me guessing until the end.', 4),
(1, 66, 'A gripping read.', 3),
(2, 66, 'Highly recommend for mystery fans.', 4),
(3, 67, 'An emotional and powerful story.', 3),
(4, 67, 'Loved the exploration of family dynamics.', 5),
(5, 67, 'Heartfelt and beautifully written.', 5),
(6, 67, 'Touching and memorable.', 4),
(7, 67, 'Couldn''t put it down.', 5),
(8, 67, 'Highly recommend this novel.', 4),
(9, 68, 'A gripping and emotional journey.', 5),
(10, 68, 'Loved the intertwining stories.', 5),
(11, 68, 'Complex characters and relationships.', 5),
(12, 68, 'Kept me engaged throughout.', 4),
(13, 68, 'Couldn''t put it down.', 5),
(14, 68, 'Highly recommend this book.', 4),
(15, 69, 'A thought-provoking exploration of memory.', 5),
(16, 69, 'Lyrical prose and deep themes.', 5),
(17, 69, 'Beautifully written and haunting.', 5),
(18, 69, 'Captivating from start to finish.', 4),
(19, 69, 'A unique and memorable read.', 3),
(20, 69, 'Highly recommend this novel.', 4),
(1, 70, 'A compelling and atmospheric tale.', 5),
(2, 70, 'Loved the setting and suspense.', 5),
(3, 70, 'Well-crafted characters and plot.', 5),
(4, 70, 'Kept me guessing until the end.', 4),
(5, 70, 'A gripping read.', 5),
(6, 70, 'Highly recommend for mystery fans.', 4);


-- read_books_lists for books from ID 71 to ID 80 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(7, 71, 'An emotional and powerful story.', 5),
(8, 71, 'Loved the exploration of family dynamics.', 3),
(9, 71, 'Heartfelt and beautifully written.', 5),
(10, 71, 'Touching and memorable.', 4),
(11, 71, 'Couldn''t put it down.', 5),
(12, 71, 'Highly recommend this novel.', 4),
(13, 72, 'A gripping and atmospheric mystery.', 5),
(14, 72, 'Kept me guessing until the end.', 5),
(15, 72, 'Well-crafted plot and characters.', 5),
(16, 72, 'Engaging and suspenseful.', 4),
(17, 72, 'A thrilling read.', 5),
(18, 72, 'Highly recommend for mystery fans.', 4),
(19, 73, 'An emotional and powerful story.', 5),
(20, 73, 'Loved the exploration of family dynamics.', 5),
(1, 73, 'Heartfelt and beautifully written.', 5),
(2, 73, 'Touching and memorable.', 4),
(3, 73, 'Couldn''t put it down.', 5),
(4, 73, 'Highly recommend this novel.', 4),
(5, 74, 'A gripping and emotional journey.', 5),
(6, 74, 'Loved the intertwining stories.', 5),
(7, 74, 'Complex characters and relationships.', 5),
(8, 74, 'Kept me engaged throughout.', 4),
(9, 74, 'Couldn''t put it down.', 5),
(10, 74, 'Highly recommend this book.', 4),
(11, 75, 'A thought-provoking exploration of memory.', 5),
(12, 75, 'Lyrical prose and deep themes.', 5),
(13, 75, 'Beautifully written and haunting.', 5),
(14, 75, 'Captivating from start to finish.', 4),
(15, 75, 'A unique and memorable read.', 5),
(16, 75, 'Highly recommend this novel.', 4),
(17, 76, 'A compelling and atmospheric tale.', 5),
(18, 76, 'Loved the setting and suspense.', 5),
(19, 76, 'Well-crafted characters and plot.', 5),
(20, 76, 'Kept me guessing until the end.', 4),
(1, 76, 'A gripping read.', 5),
(2, 76, 'Highly recommend for mystery fans.', 4),
(3, 77, 'An emotional and powerful story.', 5),
(4, 77, 'Loved the exploration of family dynamics.', 5),
(5, 77, 'Heartfelt and beautifully written.', 5),
(6, 77, 'Touching and memorable.', 4),
(7, 77, 'Couldn''t put it down.', 5),
(8, 77, 'Highly recommend this novel.', 4),
(9, 78, 'A gripping and emotional journey.', 5),
(10, 78, 'Loved the intertwining stories.', 5),
(11, 78, 'Complex characters and relationships.', 5),
(12, 78, 'Kept me engaged throughout.', 4),
(13, 78, 'Couldn''t put it down.', 5),
(14, 78, 'Highly recommend this book.', 4),
(15, 79, 'A thought-provoking exploration of memory.', 5),
(16, 79, 'Lyrical prose and deep themes.', 5),
(17, 79, 'Beautifully written and haunting.', 5),
(18, 79, 'Captivating from start to finish.', 4),
(19, 79, 'A unique and memorable read.', 5),
(20, 79, 'Highly recommend this novel.', 4),
(1, 80, 'A compelling and atmospheric tale.', 5),
(2, 80, 'Loved the setting and suspense.', 5),
(3, 80, 'Well-crafted characters and plot.', 5),
(4, 80, 'Kept me guessing until the end.', 4),
(5, 80, 'A gripping read.', 5),
(6, 80, 'Highly recommend for mystery fans.', 4);

-- read_books_lists for books from ID 81 to ID 90 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(7, 81, 'An emotional and powerful story.', 5),
(8, 81, 'Loved the exploration of family dynamics.', 5),
(9, 81, 'Heartfelt and beautifully written.', 5),
(10, 81, 'Touching and memorable.', 4),
(11, 81, 'Couldn''t put it down.', 5),
(12, 81, 'Highly recommend this novel.', 4),
(13, 82, 'A gripping and atmospheric mystery.', 5),
(14, 82, 'Kept me guessing until the end.', 5),
(15, 82, 'Well-crafted plot and characters.', 5),
(16, 82, 'Engaging and suspenseful.', 4),
(17, 82, 'A thrilling read.', 5),
(18, 82, 'Highly recommend for mystery fans.', 4),
(19, 83, 'An emotional and powerful story.', 5),
(20, 83, 'Loved the exploration of family dynamics.', 5),
(1, 83, 'Heartfelt and beautifully written.', 5),
(2, 83, 'Touching and memorable.', 4),
(3, 83, 'Couldn''t put it down.', 5),
(4, 83, 'Highly recommend this novel.', 4),
(5, 84, 'A gripping and emotional journey.', 5),
(6, 84, 'Loved the intertwining stories.', 5),
(7, 84, 'Complex characters and relationships.', 5),
(8, 84, 'Kept me engaged throughout.', 4),
(9, 84, 'Couldn''t put it down.', 5),
(10, 84, 'Highly recommend this book.', 4),
(11, 85, 'A thought-provoking exploration of memory.', 5),
(12, 85, 'Lyrical prose and deep themes.', 5),
(13, 85, 'Beautifully written and haunting.', 5),
(14, 85, 'Captivating from start to finish.', 4),
(15, 85, 'A unique and memorable read.', 5),
(16, 85, 'Highly recommend this novel.', 4),
(17, 86, 'A compelling and atmospheric tale.', 5),
(18, 86, 'Loved the setting and suspense.', 5),
(19, 86, 'Well-crafted characters and plot.', 5),
(20, 86, 'Kept me guessing until the end.', 4),
(1, 86, 'A gripping read.', 5),
(2, 86, 'Highly recommend for mystery fans.', 4),
(3, 87, 'An emotional and powerful story.', 5),
(4, 87, 'Loved the exploration of family dynamics.', 5),
(5, 87, 'Heartfelt and beautifully written.', 5),
(6, 87, 'Touching and memorable.', 4),
(7, 87, 'Couldn''t put it down.', 5),
(8, 87, 'Highly recommend this novel.', 4),
(9, 88, 'A gripping and emotional journey.', 5),
(10, 88, 'Loved the intertwining stories.', 5),
(11, 88, 'Complex characters and relationships.', 5),
(12, 88, 'Kept me engaged throughout.', 4),
(13, 88, 'Couldn''t put it down.', 5),
(14, 88, 'Highly recommend this book.', 4),
(15, 89, 'A thought-provoking exploration of memory.', 5),
(16, 89, 'Lyrical prose and deep themes.', 5),
(17, 89, 'Beautifully written and haunting.', 5),
(18, 89, 'Captivating from start to finish.', 4),
(19, 89, 'A unique and memorable read.', 5),
(20, 89, 'Highly recommend this novel.', 4),
(1, 90, 'A compelling and atmospheric tale.', 5),
(2, 90, 'Loved the setting and suspense.', 5),
(3, 90, 'Well-crafted characters and plot.', 5),
(4, 90, 'Kept me guessing until the end.', 4),
(5, 90, 'A gripping read.', 5),
(6, 90, 'Highly recommend for mystery fans.', 4);



-- read_books_lists for books from ID 91 to ID 100 with user_id between 1 and 20
INSERT INTO read_books_list (user_id, book_id, comment, rating) VALUES
(5, 91, 'A gripping read.', 5),
(6, 91, 'Highly recommend for mystery fans.', 4),
(7, 92, 'An emotional and powerful story.', 5),
(8, 92, 'Loved the exploration of family dynamics.', 5),
(9, 92, 'Heartfelt and beautifully written.', 5),
(10, 92, 'Touching and memorable.', 4),
(11, 92, 'Couldn''t put it down.', 5),
(12, 92, 'Highly recommend this novel.', 4),
(13, 93, 'A gripping and atmospheric mystery.', 5),
(14, 93, 'Kept me guessing until the end.', 5),
(15, 93, 'Well-crafted plot and characters.', 5),
(16, 93, 'Engaging and suspenseful.', 4),
(17, 93, 'A thrilling read.', 5),
(18, 93, 'Highly recommend for mystery fans.', 4),
(19, 94, 'An emotional and powerful story.', 5),
(20, 94, 'Loved the exploration of family dynamics.', 5),
(1, 94, 'Heartfelt and beautifully written.', 5),
(2, 94, 'Touching and memorable.', 4),
(3, 94, 'Couldn''t put it down.', 5),
(4, 94, 'Highly recommend this novel.', 4),
(5, 95, 'A gripping and emotional journey.', 5),
(6, 95, 'Loved the intertwining stories.', 5),
(7, 95, 'Complex characters and relationships.', 5),
(8, 95, 'Kept me engaged throughout.', 4),
(9, 95, 'Couldn''t put it down.', 5),
(10, 95, 'Highly recommend this book.', 4),
(11, 96, 'A thought-provoking exploration of memory.', 5),
(12, 96, 'Lyrical prose and deep themes.', 5),
(13, 96, 'Beautifully written and haunting.', 5),
(14, 96, 'Captivating from start to finish.', 4),
(15, 96, 'A unique and memorable read.', 5),
(16, 96, 'Highly recommend this novel.', 4),
(17, 97, 'A compelling and atmospheric tale.', 5),
(18, 97, 'Loved the setting and suspense.', 5),
(19, 97, 'Well-crafted characters and plot.', 5),
(20, 97, 'Kept me guessing until the end.', 4),
(1, 97, 'A gripping read.', 5),
(2, 97, 'Highly recommend for mystery fans.', 4),
(3, 98, 'An emotional and powerful story.', 5),
(4, 98, 'Loved the exploration of family dynamics.', 5),
(5, 98, 'Heartfelt and beautifully written.', 5),
(6, 98, 'Touching and memorable.', 4),
(7, 98, 'Couldn''t put it down.', 5),
(8, 98, 'Highly recommend this novel.', 4),
(9, 99, 'A gripping and emotional journey.', 5),
(10, 99, 'Loved the intertwining stories.', 5),
(11, 99, 'Complex characters and relationships.', 5),
(12, 99, 'Kept me engaged throughout.', 4),
(13, 99, 'Couldn''t put it down.', 5),
(14, 99, 'Highly recommend this book.', 4),
(15, 100, 'A thought-provoking exploration of memory.', 5),
(16, 100, 'Lyrical prose and deep themes.', 5),
(17, 100, 'Beautifully written and haunting.', 5),
(18, 100, 'Captivating from start to finish.', 4),
(19, 100, 'A unique and memorable read.', 5),
(20, 100, 'Highly recommend this novel.', 4);





